name: bpi2012-aml-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - azure-ai-ml>=1.15.0
      - azure-identity>=1.15.0
      - pandas>=2.0
      - numpy>=1.25
      - scikit-learn>=1.3
      - xgboost>=2.0
      - joblib>=1.3
      - pm4py>=2.7.10
      - matplotlib>=3.8
      - shap>=0.45.0
      - pyarrow>=15.0.0
      - mlflow>=2.10