$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: bpi2012-risk-endpoint

# local path to a folder containing model.joblib and feature_names.json
model: ./artifacts/model

code_configuration:
  code: ./infra/inference
  scoring_script: score.py

environment:
  image: mcr.microsoft.com/azureml/minimal-ubuntu22.04-py39-cpu-inference:latest
  conda_file: ./infra/environment-conda.yml

instance_type: Standard_DS2_v2
instance_count: 1

request_settings:
  request_timeout_ms: 60000

liveness_probe:
  initial_delay: 10
  period: 10

readiness_probe:
  initial_delay: 10
  period: 10